904 create navbar
danielowenscs/bug-wars-client pull request #38
Opened 2024-02-07 19:03 UTC by jeffelwino

Created NavBar.vue file for mobile viewing.
Refactored App.vue template and imports, as well as LogoutButton component.
Added login-logout-button global class to styles.scss.
Login/Logout button appearance will depend on whether or not there is a token present in the store AKA whether a user is logged in or not.
Hamburger menu icon is not interactive yet.

2024-02-07 23:59 UTC, danielowenscs requested changes
- height of nav bar should be 60px
- height of login button should be 28px
- when you click _Bug Wars_ it should redirect to homepage
- hamburger icon should be 24px x 24px
- hamburger icon should not have a border around it
- on hover of buttons _Bug Wars_, _Login_, _Hamburger Menu_ cursor should change to a pointer
- make horizontal padding a global variable that can be used across all components (will discuss in standup)

2024-02-08 01:16 UTC, jeffelwino commented
REPLY TO REQUESTED CHANGES:

- height of nav bar should be 60px -> DONE (~59px, but who's counting?)
- height of login button should be 28px -> DONE
- when you click Bug Wars it should redirect to homepage -> DONE
- hamburger icon should be 24px x 24px -> DONE (made 28px x 28px b/c it looked better alongside LogIn button)
- hamburger icon should not have a border around it -> NOT VISIBLE IN CHROME. ONLY A PLACEHOLDER
- on hover of buttons Bug Wars, Login, Hamburger Menu cursor should change to a pointer-> DONE. VISIBLE IN CHROME OR SAFARI, NOT ON IPHONE SIMULATOR.
- make horizontal padding a global variable that can be used across all components (will discuss in standup)-> DONE

2024-02-08 23:36 UTC, Paul-Ignagni approved these changes

2024-02-09 00:02 UTC, danielowenscs approved these changes

2024-02-09 00:11 UTC, merged